// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPrr2DP5ylT-4r1MxbGMLzGKGqSViFUU',
    appId: '1:172069779331:web:9236f54a47759c40f268b6',
    messagingSenderId: '172069779331',
    projectId: 'flutter-chat-app-c6d30',
    authDomain: 'flutter-chat-app-c6d30.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c6d30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ILRC-cWr_NJa3ikM1tQa4j5qez_4Qkc',
    appId: '1:172069779331:android:d683724951aea18ef268b6',
    messagingSenderId: '172069779331',
    projectId: 'flutter-chat-app-c6d30',
    storageBucket: 'flutter-chat-app-c6d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUD2XJdMDzPR95s3unEE0-QHSSeIi65qI',
    appId: '1:172069779331:ios:495a2700a460c487f268b6',
    messagingSenderId: '172069779331',
    projectId: 'flutter-chat-app-c6d30',
    storageBucket: 'flutter-chat-app-c6d30.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUD2XJdMDzPR95s3unEE0-QHSSeIi65qI',
    appId: '1:172069779331:ios:495a2700a460c487f268b6',
    messagingSenderId: '172069779331',
    projectId: 'flutter-chat-app-c6d30',
    storageBucket: 'flutter-chat-app-c6d30.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwPrr2DP5ylT-4r1MxbGMLzGKGqSViFUU',
    appId: '1:172069779331:web:91cc37a09ccf7b42f268b6',
    messagingSenderId: '172069779331',
    projectId: 'flutter-chat-app-c6d30',
    authDomain: 'flutter-chat-app-c6d30.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c6d30.firebasestorage.app',
  );

}